<a href="https://colab.research.google.com/github/hazeeb-ahamed/meachine-Learning/blob/main/ML_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Title of project - prediction of Hill and valley with logistic Regression using Machine Learning.

Data Source

In [ ]:
# https://github.com/YBI-Foundation/Dataset/raw/main/Hill%20Valley%20Dataset.csv

Import Library

In [ ]:
import pandas as pd
import numpy as np

Import Data

In [ ]:
df=pd.read_csv("https://github.com/YBI-Foundation/Dataset/raw/main/Hill%20Valley%20Dataset.csv")

Describe Data

In [ ]:
df.describe

<bound method NDFrame.describe of             V1        V2        V3        V4        V5        V6        V7  \
0        39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1         1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2     68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3     44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4         5.70      5.40      5.28      5.38      5.27      5.61      6.00   
...        ...       ...       ...       ...       ...       ...       ...   
1207     13.00     12.87     13.27     13.04     13.19     12.53     14.31   
1208     48.66     50.11     48.55     50.43     50.09     49.67     48.95   
1209  10160.65   9048.63   8994.94   9514.39   9814.74  10195.24  10031.47   
1210     34.81     35.07     34.98     32.37     34.16     34.03     33.31   
1211   8489.43   7672.98   9132.14   7985.73   8226.85   8554.28   8838.87   

            V8        V9     

Data Visualization

In [ ]:
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       ...
       'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100',
       'Class'],
      dtype='object', length=101)

In [ ]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0     39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1      1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2  68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3  44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4      5.70      5.40      5.28      5.38      5.27      5.61      6.00   

         V8        V9       V10  ...       V92       V93       V94       V95  \
0     39.53     38.81     38.79  ...     36.62     36.92     38.80     38.52   
1      1.70      1.75      1.78  ...      1.80      1.79      1.77      1.74   
2  73268.61  74465.84  72503.37  ...  73438.88  71053.35  71112.62  74916.48   
3  37668.32  40980.89  38466.15  ...  42625.67  40684.20  46960.73  44546.80   
4      5.38      5.34      5.87  ...      5.17      5.67      5.60      5.94   

        V96       V97       V98       V99      V100  Class  
0     38.07     36.73     39.46     37.50     39.10      0  
1      1.74      1.80      1.78      1.75      1.69      1  
2  72571.58  66348.97  71063.72  67404.27  74920.24      1  
3  45410.53  47139.44  43095.68  40888.34  39615.19      0  
4      5.73      5.22      5.30      5.73      5.91      0  

[5 rows x 101 columns]

In [ ]:
df.tail()

V1       V2       V3       V4       V5        V6        V7  \
1207     13.00    12.87    13.27    13.04    13.19     12.53     14.31   
1208     48.66    50.11    48.55    50.43    50.09     49.67     48.95   
1209  10160.65  9048.63  8994.94  9514.39  9814.74  10195.24  10031.47   
1210     34.81    35.07    34.98    32.37    34.16     34.03     33.31   
1211   8489.43  7672.98  9132.14  7985.73  8226.85   8554.28   8838.87   

            V8       V9      V10  ...      V92      V93      V94      V95  \
1207     13.33    13.63    14.55  ...    12.48    12.15    13.15    12.35   
1208     48.65    48.63    48.61  ...    46.93    49.61    47.16    48.17   
1209  10202.28  9152.99  9591.75  ...  9068.11  9191.80  9275.04  9848.18   
1210     32.48    35.63    32.48  ...    32.76    35.03    32.89    31.91   
1211   8967.24  8635.14  8544.37  ...  8609.73  9209.48  8496.33  8724.01   

          V96      V97       V98      V99     V100  Class  
1207    13.58    13.86     12.88    13.87    13.51      1  
1208    47.94    49.81     49.89    47.43    47.77      0  
1209  9074.17  9601.74  10366.24  8997.60  9305.77      1  
1210    33.85    35.28     32.49    32.83    34.82      1  
1211  8219.99  8550.86   8679.43  8389.31  8712.80      0  

[5 rows x 101 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Columns: 101 entries, V1 to Class
dtypes: float64(100), int64(1)
memory usage: 956.5 KB


Data Preprocessing

In [ ]:
print(df.columns.tolist())

['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100', 'Class']


Define Target variable (y) and Feature Variable (X)

In [ ]:
y=df['Class']

In [ ]:
y.shape

(1212,)

In [ ]:
y

0       0
1       1
2       1
3       0
4       0
       ..
1207    1
1208    0
1209    1
1210    1
1211    0
Name: Class, Length: 1212, dtype: int64

In [ ]:
X =df.drop('Class',axis=1)

In [ ]:
X.shape

(1212, 100)

In [ ]:
X

V1        V2        V3        V4        V5        V6        V7  \
0        39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1         1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2     68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3     44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4         5.70      5.40      5.28      5.38      5.27      5.61      6.00   
...        ...       ...       ...       ...       ...       ...       ...   
1207     13.00     12.87     13.27     13.04     13.19     12.53     14.31   
1208     48.66     50.11     48.55     50.43     50.09     49.67     48.95   
1209  10160.65   9048.63   8994.94   9514.39   9814.74  10195.24  10031.47   
1210     34.81     35.07     34.98     32.37     34.16     34.03     33.31   
1211   8489.43   7672.98   9132.14   7985.73   8226.85   8554.28   8838.87   

            V8        V9       V10  ...       V91       V92       V93  \
0        39.53     38.81     38.79  ...     37.57     36.62     36.92   
1         1.70      1.75      1.78  ...      1.71      1.80      1.79   
2     73268.61  74465.84  72503.37  ...  69384.71  73438.88  71053.35   
3     37668.32  40980.89  38466.15  ...  47653.60  42625.67  40684.20   
4         5.38      5.34      5.87  ...      5.52      5.17      5.67   
...        ...       ...       ...  ...       ...       ...       ...   
1207     13.33     13.63     14.55  ...     12.89     12.48     12.15   
1208     48.65     48.63     48.61  ...     47.45     46.93     49.61   
1209  10202.28   9152.99   9591.75  ...  10413.41   9068.11   9191.80   
1210     32.48     35.63     32.48  ...     33.18     32.76     35.03   
1211   8967.24   8635.14   8544.37  ...   7747.70   8609.73   9209.48   

           V94       V95       V96       V97       V98       V99      V100  
0        38.80     38.52     38.07     36.73     39.46     37.50     39.10  
1         1.77      1.74      1.74      1.80      1.78      1.75      1.69  
2     71112.62  74916.48  72571.58  66348.97  71063.72  67404.27  74920.24  
3     46960.73  44546.80  45410.53  47139.44  43095.68  40888.34  39615.19  
4         5.60      5.94      5.73      5.22      5.30      5.73      5.91  
...        ...       ...       ...       ...       ...       ...       ...  
1207     13.15     12.35     13.58     13.86     12.88     13.87     13.51  
1208     47.16     48.17     47.94     49.81     49.89     47.43     47.77  
1209   9275.04   9848.18   9074.17   9601.74  10366.24   8997.60   9305.77  
1210     32.89     31.91     33.85     35.28     32.49     32.83     34.82  
1211   8496.33   8724.01   8219.99   8550.86   8679.43   8389.31   8712.80  

[1212 rows x 100 columns]

Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.3, stratify=y, random_state=2559)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((848, 100), (364, 100), (848,), (364,))

Modeling / get model train

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
Ir=LogisticRegression()

In [ ]:
Ir.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

Prediction

In [ ]:
y_pred =Ir.predict(X_test)

In [ ]:
y_pred.shape

(364,)

In [ ]:
y_pred

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,

Probability of Each predicted Class

In [ ]:
Ir.predict_proba(X_test)

array([[5.99841069e-001, 4.00158931e-001],
       [9.99957826e-001, 4.21740626e-005],
       [0.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 1.47704928e-107],
       [1.00000000e+000, 9.60622523e-024],
       [0.00000000e+000, 1.00000000e+000],
       [5.37062954e-001, 4.62937046e-001],
       [1.00000000e+000, 3.97659911e-168],
       [0.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 3.93142688e-265],
       [1.00000000e+000, 1.10473860e-275],
       [1.00000000e+000, 0.00000000e+000],
       [2.77065326e-001, 7.22934674e-001],
       [9.99990721e-001, 9.27882386e-006],
       [1.00000000e+000, 4.31819093e-058],
       [1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [3.53120894e-001, 6.46879106e-001],
       [4.68514116e-014, 1.00000000e+000],
       [8.01309889e-001, 1.98690111e-001],
       [9.00392442e-001, 9.96075581e-002],
       [4.13356325e-001, 5.86643675e-001],
       [5.7

Get model Evaluation

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.98      0.95       182
           1       0.98      0.93      0.95       182

    accuracy                           0.95       364
   macro avg       0.95      0.95      0.95       364
weighted avg       0.95      0.95      0.95       364



In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[178   4]
 [ 13 169]]


Some future Preddiction

In [ ]:
X_new=df.sample(1)
X_new

V1      V2       V3       V4       V5       V6       V7       V8  \
196  5374.17  5499.7  5721.86  5910.44  5008.95  5044.35  4987.98  4915.21   

          V9      V10  ...      V92      V93      V94      V95      V96  \
196  5137.63  5245.55  ...  5924.43  5932.34  5885.85  5041.23  5031.43   

         V97      V98      V99     V100  Class  
196  5041.26  5210.02  5277.05  5717.25      1  

[1 rows x 101 columns]

In [ ]:
X_new.shape

(1, 101)

In [ ]:
X_new = X_new.drop('Class', axis = 1)
X_new

V1      V2       V3       V4       V5       V6       V7       V8  \
196  5374.17  5499.7  5721.86  5910.44  5008.95  5044.35  4987.98  4915.21   

          V9      V10  ...      V91      V92      V93      V94      V95  \
196  5137.63  5245.55  ...  5275.12  5924.43  5932.34  5885.85  5041.23   

         V96      V97      V98      V99     V100  
196  5031.43  5041.26  5210.02  5277.05  5717.25  

[1 rows x 100 columns]

In [ ]:
X_new.shape

(1, 100)

In [ ]:
y_pred_new =Ir.predict(X_new)

In [ ]:
y_pred_new

array([1])

In [ ]:
Ir.predict_proba(X_new)

array([[0., 1.]])